#!/bin/bash
# Installs [Application] [Version if locked]

app_name="empty"  #This is the name of the application. Should be lower case.
file_type="tar.gz"  #Defaults to tar.gz, but is used to determine how to uncompress the installation. "tar.XX" and "zip" are valid
proj_dir="$HOME/projects/$app_name"  #Change if you want installed in a different location
simlink="$HOME/bin/$app_name"  #Change if you want the executable called something different than $app_name
url="empty"  #URL for the project to get the binaries
checksum=true  #If you want to check the download's checksum, leave true. Requires the versha variable as the sha256sum to validate against
versha="empty"
linker=true #If this package creates a custom folder for each version and you want a consistant path for the symbolic link.

# This is an exampl for dynamically getting and setting the sha256sum from a repo.
wget https://github.com/example/myapp/releases/download/v0.2.4/checksums.txt
versha=$(grep "Linux_x86_64.tar.gz$" checksums.txt | awk '{print $1}')
rm ./checksums.txt

# Now we can call the installer function. Requires 8 things
install_software "$app_name" "$file_type" "$proj_dir" "$simlink" "$url" "$checksum" "$versha" "$linker"
